export const TOGGLE_DEVICE = 'TOGGLE_DEVICE'

export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR'

export const EXPAND_MENU = 'EXPAND_MENU'

export const SWITCH_EFFECT = 'SWITCH_EFFECT'

export const MUTATE_LOADER_STATE = 'MUTATE_LOADER_STATE'

export const MUTATE_ERRORS_STATE = 'MUTATE_ERRORS_STATE'

export const MUTATE_LOGIN_STATE = 'MUTATE_LOGIN_STATE'

export const MUTATE_MESSAGE_STATE = 'MUTATE_MESSAGE_STATE'

export const MUTATE_LOGIN_MESSAGE = 'MUTATE_LOGIN_MESSAGE'

export const MUTATE_USER_NAME = 'MUTATE_USER_NAME'
